### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by NatoBoram** [IrisShaders/Iris#18]
Hi! I'm looking to build this project, but I don't quite get it.

When I run `gradlew build`, I get this error : 

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 809ms

**Comment by NatoBoram** [comment]
Wrong command, I had to use `gradle build`. Sorry about that!

**Comment by coderbot16** [comment]
Building with ./gradlew should work just fine, if it fails then that's a bit concerning.

**Comment by WalkerKnapp** [comment]
This looks like the error you get when running new Gradle versions using JDK 7. Your global Gradle install is probably old, so it works with that Java version.

**Comment by NatoBoram** [comment]
Here's my global config at the moment.

```yaml
------------------------------------------------------------
Gradle: 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          15.0.1 (Oracle Corporation 15.0.1+9-18)
OS:           Windows 10 10.0 amd64
```

```yaml
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9-18)
OpenJDK 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```

```yaml
OS: Windows 10 Pro x86_64
Kernel: 10.0.19042
CPU: Intel i5-3570K (4) @ 3.470GHz
Memory: 10027MiB / 24519MiB
```

Is there something out of date?
